name: Check

on:
  push:
    branches:
      - "**"

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format Check
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      - name: Check formatting
        working-directory: ./frontend
        run: pnpm run format:check

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      - name: Run linter
        working-directory: ./frontend
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      - name: Run build
        working-directory: ./frontend
        env:
          PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
          NEXT_PUBLIC_PUSHER_APP_KEY: ${{ vars.NEXT_PUBLIC_PUSHER_APP_KEY }}
          PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
          NEXT_PUBLIC_PUSHER_CLUSTER: ${{ vars.NEXT_PUBLIC_PUSHER_CLUSTER }}
        run: pnpm run build
